spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.78.217:3306/pxt?characterEncoding=utf-8&useSSL=false
    username: root
    password: pxt123
#  jpa:
#    show-sql: true